### ISSUE TITLE
curl automatic updater issue (Ubuntu 16.04)

### ISSUE THREAD

**Issue by andrew804** [matthijs2704/vapor-apns#28]
When running for the first time in a fresh Ubuntu docker container i get the following output:

> 7.47.0
> Your current version of curl is out of date!
> VaporAPNS will not work with this version of curl.
> You can update curl yourself or we can try to update curl and it's nescessary dependencies.
> Continue installing curl? [y/n]
> Error: Run failed.

So in my code I set the `options.forceCurlInstall = true` which should be the equivalent of answering `y` on the command line to the above. When I build and run again the automatic curl updater does its work and returns:

> Installing nghttp2 build dependencies... [Done]
> Cloning nghttp2... [Done]
> Building nghttp2... [Done]
> Installing nghttp2... [Done]
> Downloading curl... [Done]
> Unpacking curl... [Done]
> Building curl... [Done]
> Installinstall_curl.sh: 5: install_curl.sh: sudo: not found
> Installing curl... [Done]
> Cleaning up... [Done]
> 🚀 Done! Now restart your Vapor project and all should be working!

But when I restart I get this issue:

> vapor: /usr/local/lib/libcurl.so.4: no version information available (required by ...)

Which, due to other dependencies in my app, is a problem.

**Comment by andrew804** [comment]
@alexaubry I see this is an issue when using your `aleksaubry/swift-docker:xenial-3.0.1` image with libcurl and HTTP/2 support preinstalled too. Is this not a problem for you?
@vlider @gomfucius are you still getting this warning when you run your setups?

**Comment by matthijs2704** [comment]
That should not an error, as far as I know ;) That's just a warning you can ignore. It should work just fine!

**Comment by matthijs2704** [comment]
But I see the installation of curl failed because sudo was not found. (`Installinstall_curl.sh: 5: install_curl.sh: sudo: not found
`) Make sure the sudo command is installed `apt-get install sudo`

**Comment by matthijs2704** [comment]
Or you can just execute `ln -fs /usr/local/bin/curl /usr/bin/curl`, that finishes the installation

**Comment by andrew804** [comment]
I hadn't actually tested properly, for some reason I thought it wasn't sending the notifications but I have just verified that it does! Also the other dependency issue that I thought I had was completely unrelated.

Thank you for your time and thank you for a great package 🎉 🚀

**Comment by mdab121** [comment]
This doesn't seem to fix the problem for me. Either installing curl manually with nghttp2, or with the automatic update.

`vapor build` gives me the error:
`vapor: /usr/local/lib/libcurl.so.4: no version information available (required by (...)/libFoundation.so)`

And later, after ignoring this issue and proceeding to build, I get linking errors:

```
Linking ./.build/debug/Server
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_slist_free_all@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_version@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_cleanup@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_slist_append@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_add_handle@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_init@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_init@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_setopt@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_assign@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_getinfo@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_socket_action@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_remove_handle@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_global_init@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_multi_info_read@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_easy_pause@CURL_OPENSSL_3'
/home/username/.swiftenv/versions/3.0.2/usr/lib/swift/linux/libFoundation.so: undefined reference to `curl_version_info@CURL_OPENSSL_3'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

Any help? :(

**Comment by andrew804** [comment]
@mdab121 getting the warning `vapor: /usr/local/lib/libcurl.so.4: no version information available (required by (...)/libFoundation.so)` is okay, you've just gotta ignore it.

As for those linking errors, I don't know, but just in case this is how I installed nghttp2 and curl v7.51.0 in my docker container:

```
# Install nghttp2
WORKDIR /root
RUN apt-get update && \
	apt-get install -y make gcc gcc-multilib git tmux vim htop g++ make binutils autoconf automake autotools-dev \
	libtool pkg-config zlib1g-dev libcunit1-dev libssl-dev libxml2-dev libev-dev libevent-dev libjansson-dev \
	libc-ares-dev libjemalloc-dev cython python3-dev python3-setuptools
RUN git clone https://github.com/nghttp2/nghttp2.git && \
	cd nghttp2 && \
	autoreconf -i && \
	automake && \
	autoconf && \
	./configure --enable-lib-only --prefix=/usr && \
	make && \
	make install && \
	cd / && \
    rm -r /root/nghttp2


# Install curl
# (Turnstile Web does not work with curl version 7.52.1)
ENV CURL_VERSION 7.51.0
WORKDIR /root
RUN apt-get update && \
	apt-get -y build-dep curl
RUN wget https://curl.haxx.se/download/curl-$CURL_VERSION.tar.gz && \
    tar -zxf curl-$CURL_VERSION.tar.gz && \
    cd curl-$CURL_VERSION && \
    ./configure --with-nghttp2=/usr --prefix=/usr --with-ssl --enable-ipv6 && \
    make && \
    make install && \
	ln -fs /usr/lib/libcurl.so.4 /usr/lib/x86_64-linux-gnu && \
	ln -fs /usr/lib/libcurl.so.4.4.0 /usr/lib/x86_64-linux-gnu && \
    ldconfig && \
    cd / && \
    rm -r /root/curl-$CURL_VERSION.tar.gz && \
    rm -r /root/curl-$CURL_VERSION && \
    rm -r /usr/share/man
```

**Comment by mdab121** [comment]
I've done pretty much the same thing. I just didn't install curl with ipv6 and did not include prefixes in /usr, so both curl and nghttp2 were installed in /usr/local.


The version I had was 7.52.1 though...

Also, I'm running Ubuntu 14.04.5 LTS.

Why did you run
```
ln -fs /usr/lib/libcurl.so.4 /usr/lib/x86_64-linux-gnu
ln -fs /usr/lib/libcurl.so.4.4.0 /usr/lib/x86_64-linux-gnu
```
?

**Comment by andrew804** [comment]
Thinking about it I may have run into the same linking errors as you when I was working on it but I can't remember exactly now. Try installing in `/usr` and see if you get the same linking errors.

Embarrassing as it is, I also can't remember why I included:
```
ln -fs /usr/lib/libcurl.so.4 /usr/lib/x86_64-linux-gnu
ln -fs /usr/lib/libcurl.so.4.4.0 /usr/lib/x86_64-linux-gnu
```
