### ISSUE TITLE
Build failing on Heroku

### ISSUE THREAD

**Issue by yoshimkd** [matthijs2704/vapor-apns#17]
Hello,

I've spent almost a day trying to fix my build on Heroku after introducing vapor-apns. Locally, it worked great, but when I tried to push to the Heroku repository, I always got the following build error:

Linking ./.build/release/App
/tmp/build_6ea42bc7d7da2139e7c3f372f2fdc6c9/.build/release/VaporAPNS.build/VaporAPNS.swift.o:/tmp/build_6ea42bc7d7da2139e7c3f372f2fdc6c9/.build/release/VaporAPNS.build/ApplePushMessage.swift.o:function _TTSf4g_gs_n___TFC9VaporAPNS9VaporAPNS4sendfTVS_16ApplePushMessage2toSS_OS_6Result: error: undefined reference to '_TFE8VaporJWTPS_19SignatureVerifiable19verifySignatureWithfzPS_6Signer_Sb'
clang-3.7: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
swift-build: error: exit(1): /app/.swiftenv/versions/3.0/usr/bin/swift-build-tool -f /tmp/build_6ea42bc7d7da2139e7c3f372f2fdc6c9/.build/release.yaml

I've tried to isolate the problem and got to the point of initializing a Vapor project from their default template and adding:
.Package(url: "https://github.com/matthijs2704/vapor-apns.git", majorVersion: 1, minor: 1)
to the Package.swift file. I didn't add any code to the template.

As I investigated, this will maybe be fixed by making a new release which would include the latest 3 commits (so far), they seem to be related.

Thanks in advance,
Jovan

**Comment by matthijs2704** [comment]
I've released 1.1.1 containing the new VaporJWT version. The issue had nothing to so with VaporAPNS but with VaporJWT (at least it looks/sounds like that). I'm closing this issue for now, feel free to reopen this issue if you're still experiencing this issue!

Thanks!

**Comment by yoshimkd** [comment]
Thanks for the release, but the same issue is still there... :(
I've tested the same case with older versions of your library and got it building (without coding anything) on Heroku only with version 1.0.2.

**Comment by matthijs2704** [comment]
Be sure to clean the whole Packages folder, minor releases like this tend to not come through as an update on the Swift Package Manager. ('vapor clean'). I'm not familiar with how Heroku works, so I'm not sure how things go here. I am in contact with someone who is using the latest version with heroku, I'll ask him if he knows whats wrong...

**Comment by yoshimkd** [comment]
I've checked the version used and the logs say it's the right one:

Cloning https://github.com/matthijs2704/vapor-apns.git
HEAD is now at 0e8abfa Few changes required for VaporJWT
Resolved version: 1.1.1

**Comment by marcregan** [comment]
@yoshimkd Were you able to find a workaround for this issue?

**Comment by yoshimkd** [comment]
@marcregan The only version of the library with which the Heroku build passed for me was 1.0.2. But that version as probably all others won't work on Heroku since the library uses HTTP/2 and Heroku doesn't support that. In the end I had to abandon using this library and find another solution.

**Comment by matthijs2704** [comment]
I'm closing this issue for now. Even if the extension will build on Heroku, you won't be able to use it, as Heroku lacks HTTP/2 on their routers. (Also see https://devcenter.heroku.com/articles/http-routing#http-versions-supported).

Until Heroku starts supporting HTTP/2, Heroku will not be supported by VaporAPNS (or APNS at all, as Apple's Push Notification service is based on HTTP/2)

**Comment by yoshimkd** [comment]
Just a side note, I'm not sure about this, but I think that Apple still supports the legacy version of interaction with APNS (via HTTPS) which doesn't require HTTP/2.

**Comment by matthijs2704** [comment]
Yep I know, but it's something I do not want to support. It's old and deprecated... Also the responses/results of the sent notifications are handled super weird in that version...

**Comment by marcregan** [comment]
Ah, got it. Thanks so much for looking into this!

**Comment by marcregan** [comment]
Interesting, I don't think this error is related to Heroku. Turns out I get this same error on my mac if I build vapor with the --release flag: `vapor build --release`. Same thing if I build in release mode on Ubuntu 16.04.

Error:
```
Compile Swift Module 'App' (11 sources)
Linking ./.build/release/App
Undefined symbols for architecture x86_64:
  "__TFE8VaporJWTPS_19SignatureVerifiable19verifySignatureWithfzPS_6Signer_Sb", referenced from:
      __TTSf4g_gs_n___TFC9VaporAPNS9VaporAPNS4sendfTVS_16ApplePushMessage2toSS_OS_6Result in VaporAPNS.swift.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by matthijs2704** [comment]
@marcregan Hmm, looks like it's a combination between VaporJWT and VaporAPNS. I contacted the dev of VaporJWT, we're looking into it.

**Comment by matthijs2704** [comment]
Should work now! Just clean and rebuild and it should work now. It was a bug in VaporJWT which is now fixed :)

**Comment by siemensikkema** [comment]
thanks for the hint @marcregan!

**Comment by matthijs2704** [comment]
Apparently the Swift compiler handles debug and release builds completely different, as it wasn't an issue with debug builds but it was with release builds

**Comment by marcregan** [comment]
YES! Thanks guys! 👍 🙏
